import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@components/header/Header";
import Footer from "@components/footer/Footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { I18nProviderClient } from "@/src/locales/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params: { locale },
  children,
}: Readonly<{ params: { locale: string }; children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <I18nProviderClient locale={locale}>
          <UserProvider>
            <Header />
            {children}
            <Footer />
          </UserProvider>
        </I18nProviderClient>
      </body>
    </html>
  );
}
